## A place an AI can take cover. Authored by level designers or generated by CoverGenerator.
## `wall_normal` points away from the wall (towards where the AI stands); LOW cover lets the AI peek over,
## HIGH cover (full wall) needs a side peek.
## Authority: HOST (claims are host-side AI state)
class_name CoverPoint
extends Marker3D

enum Height { LOW, HIGH }

const GROUP: StringName = &"cover_points"
const CROUCH_EYE: float = 0.9
const STAND_EYE: float = 1.6
const SIDE_PEEK: float = 0.65

@export var height: Height = Height.LOW
@export var wall_normal: Vector3 = Vector3.FORWARD

var claimed_by: Node = null


func _enter_tree() -> void:
	add_to_group(GROUP)


func is_free_for(agent: Node) -> bool:
	return claimed_by == null or claimed_by == agent or not is_instance_valid(claimed_by)


## Where the AI's eyes are while hiding here.
func get_hide_eye() -> Vector3:
	return global_position + Vector3(0, CROUCH_EYE, 0)


## Positions the AI can shoot from when it pops out.
func get_peek_eyes() -> Array[Vector3]:
	if height == Height.LOW:
		return [global_position + Vector3(0, STAND_EYE, 0)]
	var side: Vector3 = wall_normal.cross(Vector3.UP).normalized() * SIDE_PEEK
	return [global_position + side + Vector3(0, STAND_EYE, 0), global_position - side + Vector3(0, STAND_EYE, 0)]
